apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-secret
  data:
  - secretKey: username
    remoteRef:
      key: secret/data/nextcloud/secret
      property: username
  - secretKey: password
    remoteRef:
      key: secret/data/nextcloud/secret
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-nextcloud-secret
  namespace: identity
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mariadb-nextcloud-secret
  data:
  - secretKey: mariadb-username
    remoteRef:
      key: secret/data/mariadb/nextcloud/secret
      property: mariadb-username
  - secretKey: mariadb-password
    remoteRef:
      key: secret/data/mariadb/nextcloud/secret
      property: mariadb-password
  - secretKey: mariadb-root-password
    remoteRef:
      key: secret/data/mariadb/nextcloud/secret
      property: mariadb-root-password