apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-secret
  data:
  - secretKey: nextcloud-username
    remoteRef:
      key: secret/data/nextcloud/secret
      property: nextcloud-username
  - secretKey: nextcloud-password
    remoteRef:
      key: secret/data/nextcloud/secret
      property: nextcloud-password
  - secretKey: smpt-username
    remoteRef:
      key: secret/data/nextcloud/secret
      property: smpt-username
  - secretKey: smpt-password
    remoteRef:
      key: secret/data/nextcloud/secret
      property: smpt-password      
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-nextcloud-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mariadb-nextcloud-secret
  data:
  - secretKey: mariadb-username
    remoteRef:
      key: secret/data/mariadb/nextcloud/secret
      property: mariadb-username
  - secretKey: mariadb-password
    remoteRef:
      key: secret/data/mariadb/nextcloud/secret
      property: mariadb-password
  - secretKey: mariadb-root-password
    remoteRef:
      key: secret/data/mariadb/nextcloud/secret
      property: mariadb-root-password
      