filepath: ""
#environments:
#  default:
#    values:
#    - ../../default.yaml
namespace: portainer
repositories:
- name: portainer
  url: https://portainer.github.io/k8s/
releases:
- chart: portainer/portainer
  version: 3.12.0
  name: nginx-ingress
  values:
  - values.yaml
templates: {}
renderedvalues: {}
