filepath: ""
environments:
  default:
    values:
    - ../../default.yaml
repositories:
- name: nextcloud
  url: https://nextcloud.github.io/helm/
releases:
- chart: ../charts/addon
  name: addon
- chart: nextcloud/nextcloud
  version: 2.14.2
  name: nextcloud
  values:
  - values.yaml.gotmpl
templates: {}
renderedvalues: {}
