apiVersion: v1
kind: Pod
metadata:
  name: rclone-server
spec:
    containers:
    - name: rclone
      image: rclone/rclone:1.58.1
      imagePullPolicy: IfNotPresent
      command: ["rclone"]
      args: ["rcd", "--rc-web-gui", "--rc-web-gui-no-open-browser",  "--rc-addr", ":5572"]
      ports:
      - containerPort: 5572
      volumeMounts:
      - name: config
        mountPath: "/config/rclone"
      - name: data
        mountPath: "/data"
    volumes:
    - name: config
    - name: data

