apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postfix-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postfix-secret
  data:
  - secretKey: RELAYHOST_PASSWORD
    remoteRef:
      key: secret/data/postfix/secret
      property: RELAYHOST_PASSWORD
  - secretKey: RELAYHOST_USERNAME
    remoteRef:
      key: secret/data/postfix/secret
      property: RELAYHOST_USERNAME
#  - secretKey: XOAUTH2_CLIENT_ID
#    remoteRef:
#      key: secret/data/postfix/secret
#      property: XOAUTH2_CLIENT_ID
#  - secretKey: XOAUTH2_SECRET
#    remoteRef:
#      key: secret/data/postfix/secret
#      property: XOAUTH2_SECRET
#  - secretKey: XOAUTH2_INITIAL_ACCESS_TOKEN
#    remoteRef:
#      key: secret/data/postfix/secret
#      property: XOAUTH2_INITIAL_ACCESS_TOKEN
#  - secretKey: XOAUTH2_INITIAL_REFRESH_TOKEN
#    remoteRef:
#      key: secret/data/postfix/secret
#      property: XOAUTH2_INITIAL_REFRESH_TOKEN
