apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kaniko-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kaniko-secret
  data:
  - secretKey: config.json
    remoteRef:
      key: secret/data/kaniko/secret
      property: config.json
