apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-nextcloud
spec:
  workspaces:
  - name: pipeline-ws
  - name: dockerconfig
  params: 
  - name: nextcloud-image
    type: string
    description: "Nextcloud image to build"
  - name: nextcloud-version
    type: string
    description: "Nextcloud version to build"
  - name: nextcloud-dir
    type: string
    description: "Nextcloud dir containing Dockerfile"
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
      - name: url
        value: "https://github.com/lucaiacono2275/k8s-apps"
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-image
      taskRef:
        name: kaniko
      params:
      - name: IMAGE
        value: $(params.nextcloud-image):$(params.nextcloud-version)
      - name: EXTRA_ARGS
        value: 
          - "--build-arg"
          - "VERSION=$(params.nextcloud-version)"
      - name: CONTEXT
        value: nextcloud/images/$(params.nextcloud-dir)
      workspaces:
      - name: source
        workspace: pipeline-ws
      - name: dockerconfig
        workspace: dockerconfig
      runAfter:
        - clone



